import type { CoursePresentationConfig } from "@/types/course-presentation";

// Marketing videos live on Mux with a public playback policy; the poster is
// generated by Mux from the playback ID.
export const YOGA_PRESENTATION = {
  courseTitles: ["Yoga su misura", "Tailored Yoga"],
  namespace: "Yoga",
  video: { playbackId: "xVITxZMp01jhM5FkJ401cGb5WhLvT02eVhBAxUvZuR400024" },
} as const satisfies CoursePresentationConfig;

export const COURSE_PRESENTATIONS: readonly CoursePresentationConfig[] = [
  YOGA_PRESENTATION,
];
