autoInstallPeers: false

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild@0.28.1

overrides:
  sharp: ^0.35.4
